### ISSUE TITLE
Logtalk crashes on startup

### ISSUE THREAD

**Issue by baovitt** [sandogeorge/webtalk#21] opened 2023-04-04 11:30 UTC
Years ago, I investigated webtalk and thought I'd take another look at it. I was able to get it working then, but it seems to crash every time I make a request when the server starts. 

I'm use Swi-Prolog version 8.4.2 and Logtalk version 3.64.0-1. I'm using Ubuntu 20.04. There's also a stack trace:
```
SWI-Prolog [thread 8 (httpd@5000_5) at Mon Apr  3 17:46:51 2023]: received fatal signal 11 (segv)
C-stack trace labeled "crash":
  [0] PL_advance_hash_table_enum() at ??:? [0x7fe7936b8b6a]
  [1] Sdprintf() at ??:? [0x7fe7936bda4d]
  [2] PL_changed_cwd() at ??:? [0x7fe7936c3cd7]
  [3] __restore_rt() at libc_sigaction.c:? [0x7fe793242520]
  [4] EVP_MAC_up_ref() at ??:? [0x7fe791f99224]
  [5] ??() at ??:0 [0x7fe792e316c4]
  [6] PL_malloc_atomic() at ??:? [0x7fe7936ce96d]
  [7] PL_open_foreign_frame() at ??:? [0x7fe7936d4cb3]
  [8] PL_destroy_engine() at ??:? [0x7fe79369ade3]
  [9] start_thread() at ./nptl/pthread_create.c:442 [0x7fe793294b43]
  [10] __clone3() at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:83 [0x7fe793326a00]
Prolog stack:
  [35] crypto:_crypto_hash_context_copy/2 [PC=1 in supervisor]
  [34] crypto:crypto_data_context/3 [PC=5 in clause 1]
  [33] crypto:crypto_data_hash/3 [PC=13 in clause 1]
  [32] $form#0.init#0/1 [PC=52 in clause 1]
  [31] $lgt_send_to_obj_ne_nv/3 [PC=204 in clause 1]
  [27] $lgt_send_to_obj_ne_nv/3 [PC=144 in clause 1]
  [25] $install#0.install#1/2 [PC=218 in clause 1]
  [24] $lgt_send_to_obj_ne_nv/3 [PC=144 in clause 1]
  [22] system:catch/3 [PC=2 in clause 1]
  [20] call/1 [PC=3 in clause 1]
  [19] yall:>>/3 [PC=30 in clause 1]
  [18] http_dispatch:call_action/2 [PC=8 in clause 1]
  [16] time:run_alarm_goal/2 [PC=6 in clause 1]
  [15] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
  [13] time:call_with_time_limit/2 [PC=40 in clause 1]
  [12] http_dispatch:time_limit_action/3 [PC=53 in clause 1]
  [8] httpd_wrapper:call_handler/3 [PC=35 in clause 2]
  [7] system:catch/3 [PC=2 in clause 1]
  [6] httpd_wrapper:handler_with_output_to/5 [PC=24 in clause 1]
  [5] httpd_wrapper:handler_with_output_to/5 [PC=18 in clause 2]
  [4] httpd_wrapper:http_wrapper/5 [PC=166 in clause 1]
  [3] thread_httpd:http_process/4 [PC=64 in clause 1]
  [2] system:catch/3 [PC=2 in clause 1]
  [1] thread_httpd:http_worker/1 [PC=168 in clause 1]
  [0] system:$c_call_prolog/0 [PC=0 in top query clause]
Running on_halt hooks with status 139
Killing 20193 with default signal handlers
Segmentation fault (core dumped)
```

I'm just wondering if anyone has any clear idea of how I might be able to fix this.

**Comment by sandogeorge** [comment] 2023-04-05 04:26
Hi @baovitt. I myself haven't looked at the code in about 5 years. I will give it a shot this weekend and give you an update.

**Comment by baovitt** [comment] 2023-04-10 18:40
Did you get a chance to take a look?

**Comment by sandogeorge** [comment] 2023-04-12 07:39
Hey, I finally did get a chance. It seems there was [an issue](https://github.com/SWI-Prolog/swipl-devel/issues/1014) with the way some versions of SWI handled the crypto package. I upgraded to version 9.0.4 and it works. I also made some updates to the code for a few minor issues I found. Let me know how it goes.

**Comment by baovitt** [comment] 2023-04-14 20:32
I get the same error my machine.

**Comment by sandogeorge** [comment] 2023-04-15 06:18
Did you update your version of SWI Prolog? Which version are you using?

**Comment by sandogeorge** [comment] 2023-04-19 08:35
I'm closing because I have found sufficient evidence that the segfault was due to compatibility issues between versions of Debian, SWI-Prolog and its crypto package. I successfully reproduced the issue on Ubuntu 22.04 running SWI-Prolog 8.4.2 and Logtalk 3.64.0. I was able to resolve it by updating SWI-Prolog to version 9.0.4.

**Closed as completed by sandogeorge** 2023-04-19 08:35 UTC
